/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { InternetFriendsCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$passkeysGetGenerateAuthenticateOptions } from "./tools/passkeysGetGenerateAuthenticateOptions.js";
import { tool$passkeysGetGenerateRegisterOptions } from "./tools/passkeysGetGenerateRegisterOptions.js";
import { tool$passkeysVerifyAuthentication } from "./tools/passkeysVerifyAuthentication.js";
import { tool$passkeysVerifyRegistration } from "./tools/passkeysVerifyRegistration.js";
import { tool$sessionsDestroy } from "./tools/sessionsDestroy.js";
import { tool$sessionsRenew } from "./tools/sessionsRenew.js";
import { tool$sessionsStatus } from "./tools/sessionsStatus.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL: string;
  sessionAuth?: SDKOptions["sessionAuth"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "InternetFriends",
    version: "0.1.2",
  });

  const client = new InternetFriendsCore({
    sessionAuth: deps.sessionAuth,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$passkeysGetGenerateAuthenticateOptions);
  tool(tool$passkeysGetGenerateRegisterOptions);
  tool(tool$passkeysVerifyAuthentication);
  tool(tool$passkeysVerifyRegistration);
  tool(tool$sessionsStatus);
  tool(tool$sessionsRenew);
  tool(tool$sessionsDestroy);

  return server;
}
