/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsStatus } from "../../funcs/sessionsStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$sessionsStatus: ToolDefinition = {
  name: "sessions-status",
  description: `Check session status

Validates the current session and returns user information`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await sessionsStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
