/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { sessionsRenew } from "../../funcs/sessionsRenew.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$sessionsRenew: ToolDefinition = {
  name: "sessions-renew",
  description: `Renew session

Creates a new session token and extends the session duration`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await sessionsRenew(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
