/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type PasskeyVerificationRequest = {
  /**
   * JSON stringified WebAuthn response
   */
  response: string;
};

/** @internal */
export const PasskeyVerificationRequest$inboundSchema: z.ZodType<
  PasskeyVerificationRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  response: z.string(),
});

/** @internal */
export type PasskeyVerificationRequest$Outbound = {
  response: string;
};

/** @internal */
export const PasskeyVerificationRequest$outboundSchema: z.ZodType<
  PasskeyVerificationRequest$Outbound,
  z.ZodTypeDef,
  PasskeyVerificationRequest
> = z.object({
  response: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PasskeyVerificationRequest$ {
  /** @deprecated use `PasskeyVerificationRequest$inboundSchema` instead. */
  export const inboundSchema = PasskeyVerificationRequest$inboundSchema;
  /** @deprecated use `PasskeyVerificationRequest$outboundSchema` instead. */
  export const outboundSchema = PasskeyVerificationRequest$outboundSchema;
  /** @deprecated use `PasskeyVerificationRequest$Outbound` instead. */
  export type Outbound = PasskeyVerificationRequest$Outbound;
}

export function passkeyVerificationRequestToJSON(
  passkeyVerificationRequest: PasskeyVerificationRequest,
): string {
  return JSON.stringify(
    PasskeyVerificationRequest$outboundSchema.parse(passkeyVerificationRequest),
  );
}

export function passkeyVerificationRequestFromJSON(
  jsonString: string,
): SafeParseResult<PasskeyVerificationRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PasskeyVerificationRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PasskeyVerificationRequest' from JSON`,
  );
}
