/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Passkeys } from "./passkeys.js";
import { Sessions } from "./sessions.js";

export class InternetFriends extends ClientSDK {
  private _passkeys?: Passkeys;
  get passkeys(): Passkeys {
    return (this._passkeys ??= new Passkeys(this._options));
  }

  private _sessions?: Sessions;
  get sessions(): Sessions {
    return (this._sessions ??= new Sessions(this._options));
  }
}
