/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { InternetFriendsError } from "./internetfriendserror.js";

export type ErrorTData = {
  /**
   * Human-readable error message
   */
  error: string;
  /**
   * Machine-readable error code
   */
  code?: string | undefined;
  /**
   * Additional error details
   */
  details?: { [k: string]: any } | undefined;
  /**
   * ISO timestamp when the error occurred
   */
  timestamp?: Date | undefined;
};

export class ErrorT extends InternetFriendsError {
  /**
   * Human-readable error message
   */
  error: string;
  /**
   * Machine-readable error code
   */
  code?: string | undefined;
  /**
   * Additional error details
   */
  details?: { [k: string]: any } | undefined;
  /**
   * ISO timestamp when the error occurred
   */
  timestamp?: Date | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorTData;

  constructor(
    err: ErrorTData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.code != null) this.code = err.code;
    if (err.details != null) this.details = err.details;
    if (err.timestamp != null) this.timestamp = err.timestamp;

    this.name = "ErrorT";
  }
}

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    error: z.string(),
    code: z.string().optional(),
    details: z.record(z.any()).optional(),
    timestamp: z.string().datetime({ offset: true }).transform(v => new Date(v))
      .optional(),
    request$: z.instanceof(Request),
    response$: z.instanceof(Response),
    body$: z.string(),
  })
  .transform((v) => {
    return new ErrorT(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type ErrorT$Outbound = {
  error: string;
  code?: string | undefined;
  details?: { [k: string]: any } | undefined;
  timestamp?: string | undefined;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.instanceof(ErrorT)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
    code: z.string().optional(),
    details: z.record(z.any()).optional(),
    timestamp: z.date().transform(v => v.toISOString()).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ErrorT$ {
  /** @deprecated use `ErrorT$inboundSchema` instead. */
  export const inboundSchema = ErrorT$inboundSchema;
  /** @deprecated use `ErrorT$outboundSchema` instead. */
  export const outboundSchema = ErrorT$outboundSchema;
  /** @deprecated use `ErrorT$Outbound` instead. */
  export type Outbound = ErrorT$Outbound;
}
