name: Speakeasy CLI

on:
  pull_request:
    paths:
      - 'openapi.yaml'

jobs:
  speakeasy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Speakeasy CLI
        run: npm install -g @speakeasy-api/cli
      - name: Validate OpenAPI Spec
        run: speakeasy validate -c .speakeasy.json